### PR TITLE
Rip out broken classification system

### LINKED ISSUE #36: unicode encore error (2)
Using 8abd64bf (fix for #34) and python 2.7.2+

When running 
$ afew -v -v -d --classify -- tag:inbox

I always end up with: 
Traceback (most recent call last):
  File "/home/nrl/local/bin/afew", line 189, in <module>
    main(options, query_string)
  File "/home/nrl/local/lib/python2.7/site-packages/afew/main.py", line 69, in main
    print('%s --> %s' % (message, category))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

### PR DESCRIPTION
**Pull request by kyrias**
The classification system is currently really broken, so rip it out so
that people don't accidentally try to use it.  If someone wants to
implement it properly in the future it would be much simpler to start
from scratch.

Closes #36, #42, #92, #103, #137, #141.

---

Nuking as per [this](https://github.com/afewmail/afew/issues/92#issuecomment-307814243) comment.

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
Hey @kyrias 
Thanks for this work !

As the changes are big it would be great to have multiple review @flokli @andir

**Comment by flokli** [comment]
LGTM. @andir, what do you think?

**Comment by andir** [comment]
All I know is that it is broken go ahead.

**Comment by flokli** [comment]
nuked :-)

**Comment by kyrias** [comment]
Wooh, closing 6 issues at once :p

**Comment by GuillaumeSeren** [comment]
Nice ! @kyrias

**Pull request merged**
