### PR TITLE
Switch from optparse to argparse.

### PR DESCRIPTION
**Pull request by lucc**
This is a PR for #24.

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
Hi @lucc ,
as this solve a problem reported by author I think we should take it.

It is probably needed to add the new dependency in the 'setup.py' install file ?

**Comment by lucc** [comment]
argparse in the standard lib since 2.7 so it is not an external dependency we need to install.

**Comment by GuillaumeSeren** [comment]
@lucc LGTM but let's give some time to see if other maintainer want to add something

**Comment by GuillaumeSeren** [comment]
Merged ! thanks @lucc 👍

**Pull request merged**
