### PR TITLE
Don't interfere with the notmuch unread tag.

### PR DESCRIPTION
**Pull request by hlieberman**
Right now, afew tramples the notmuch unread tag, interfering with notmuch-el.

This patch will change that behavior to not modify the unread tag.

### CODE REVIEW

**Comment by babilen** [comment]
This would be very useful to have. For now I am using the following to approximate this behaviour:

```
[Filter.0]
message = 'Retags all messages not tagged as junk or killed as inbox'
tags = +inbox;-new
tags_blacklist = killed;spam
```

**Comment by GuillaumeSeren** [comment]
Hey @hlieberman 
I didn't notice this behaviour until reading your PR, to me it might more be something that the user can configure, than just changing the default for everybody.

**Comment by GuillaumeSeren** [comment]
Hey,
this is not moving and get no negative feedback, let's merge it.

**Comment by flokli** [comment]
This basically triggered #158.

**Comment by GuillaumeSeren** [comment]
@flokli Yes it is true,
if it is a problem we can revert it, but I've only tested them on python-2, now I'll test on both python-2 and python-3 🤖

**Pull request merged**
