### PR TITLE
Add two new filters to propagate tags in threads

### PR DESCRIPTION
**Pull request by neuhalje**

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
Hello @neuhalje,
thank you for this interresting patch, I think it could be merged, when passed the review (and rebased).

**Comment by GuillaumeSeren** [comment]
@floki @andir do you want to have a look ?

**Comment by neuhalje** [comment]
GitHub seems to have some kind of "auto merge" feature in PRs - tried that just now :-)

**Comment by neuhalje** [comment]
@rpuntaie - updated

**Comment by GuillaumeSeren** [comment]
Let's merge thank you for the patch @neuhalje

**Pull request merged**
