### PR TITLE
Inspect DMARC reports and tag the message

### PR DESCRIPTION
**Pull request by aidecoe**
DMARC reports usually come in ZIP files. To check the report you have to
unpack and search thru XML document which is very tedious. The filter
tags the message as follows:

- if there's any SPF failure in any attachment, tag the message with
"dmarc-spf-fail" tag, otherwise tag with "dmarc-spf-ok"
- if there's any DKIM failure in any attachment, tag the message with
"dmarc-dkim-fail" tag, otherwise tag with "dmarc-dkim-ok"

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
Hey @aidecoe thank you for the patch
This looks good to me and it is a external filter, so let's merge it.

**Comment by flokli** [comment]
@aidecoe Same as in #170: Could you please add an example mail for each of the 4 different tags, so they can be intergrated in the test harness?

**Comment by andir** [comment]
Why I am the author of that commit? That looks wrong o.O

**Comment by GuillaumeSeren** [comment]
Be careful @andir it's a trap we will ask you to come back on the project ! 🍺

**Comment by GuillaumeSeren** [comment]
But I think you are just the first maintainer to validate the review so GH take the first one

**Comment by aidecoe** [comment]
@andir has taken all the credit for my DMARC filter so now he provides example e-mail messages.

**Comment by andir** [comment]
@aidecoe I removed myself from the `Author` field which I never added...

**Comment by GuillaumeSeren** [comment]
@andir Yes it is automatically added when you review so, joke aside not a big deal,
but I hope this will not prevent you to review patches again in the future !

You can reply instead of approving if don't want your name in the commit 🍺 😄 🍻

**Pull request merged**
