### PR TITLE
Fix AttributeError: 'filter' object has no attribute 'remove'

### PR DESCRIPTION
**Pull request by yang-ling**
Related issue is this one: https://github.com/afewmail/afew/issues/158

### CODE REVIEW

**Comment by mkaito** [comment]
Why does notmuch_settings.get_list not return a list in the first place?

El 6 de agosto de 2017 7:23:05 GMT+01:00, SpicyCat <notifications@github.com> escribió:
>Related issue is this one: https://github.com/afewmail/afew/issues/158
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/afewmail/afew/pull/159
>
>-- Commit Summary --
>
>  * Fix AttributeError: 'filter' object has no attribute 'remove'
>
>-- File Changes --
>
>    M afew/NotmuchSettings.py (2)
>
>-- Patch Links --
>
>https://github.com/afewmail/afew/pull/159.patch
>https://github.com/afewmail/afew/pull/159.diff

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yang-ling** [comment]
@mkaito I have no idea. I am not familiar with afew's source code. Today I updated afew and met this error. This PR is how I tried to fix it. Maybe it is not the best solution but it works for me.

**Comment by mkaito** [comment]
The real question here is: why the heck does [this list comprehension](https://github.com/afewmail/afew/blob/b19a88fa1c06cc03ed6c636475cf4361b616d128/afew/configparser.py#L31) not return a list?

**Comment by yang-ling** [comment]
@mkaito  I think [this line](https://github.com/afewmail/afew/blob/b19a88fa1c06cc03ed6c636475cf4361b616d128/afew/configparser.py#L36) causes this problem.

[In Python3, filter() returns return an object which is iterable, but not a list](https://stackoverflow.com/questions/12319025/filters-in-python3)

`filter(func,data) #python 2.x` is is equivalent to `list(filter(func,data)) #python 3.x`

**Comment by flokli** [comment]
@mkaito In theory, I'm more for passing iterators around, so a filter would work here, and also allow us to get of the try/except. But I agree, the name of the `get_list` methid is really misleading and should be changed.

TBH, I'd like to see the whole custom config parsing code removed and something like ConfigObj with validators being used, even if this means the config format needs to be changed slightly.

**Comment by yang-ling** [comment]
@flokli  Hi. At first thank you for creating afew.

At this moment, afew is broken in Python3 environment.  This PR is not elegant but it works for me.

Another solution is let [get_list](https://github.com/afewmail/afew/blob/b19a88fa1c06cc03ed6c636475cf4361b616d128/afew/configparser.py#L27) really returns list. But you said ` I'm more for passing iterators around` so I guess this solution won't be chosen.

So can you accept this PR? At least this PR can make afew working in Python3 environment.
Or do you have other plan?

**Comment by GuillaumeSeren** [comment]
Hey,
If this fix at least momentarily the issue on python-3.x, it could be useful to have it to keep the tool working, for those around using that version of python.

As long as we don't break the support for python-2 as well.

**Comment by GuillaumeSeren** [comment]
Ok I have tested the patch, on my local version (with python-2.x),
it worked so I guess we can use it to fix the problem, until we go for something better.

**Comment by flokli** [comment]
closed in favor of #161 .

**Pull request closed without merging**
