### PR TITLE
FolderNameFilter now looks at all folders that a message is in.

### PR DESCRIPTION
**Pull request by GuillaumeSeren**
Switched from message.get_filename() to message.get_filenames() and added appropriate processing to handle the list of file names.

This is a rebased version of the #74

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
I have rebased the branch but not tested it intensively so I need some help on that 🍺

**Comment by varac** [comment]
I used this branch already for a while now and it works for me. But I wouldn't call this extensive testing.

**Comment by GuillaumeSeren** [comment]
@varac Thank you for the feedback 🍺 
I will let the patch wait for a bit more reviews

**Comment by flokli** [comment]
@GuillaumeSeren: I think this might need a bit usage documentation, and we probably also should start adding some tests…

**Comment by GuillaumeSeren** [comment]
Hey @flokli ,
I have added a bit of documentation in the branch, please have a look at it.

Also, I have seen the #152, that was more or less the same thing so I think,
we should merge it, then upgrade it as needed.

**Comment by GuillaumeSeren** [comment]
Ok let's merge it.

**Pull request merged**
