### PR TITLE
add .travis.yml

### PR DESCRIPTION
**Pull request by flokli**

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
👍

**Comment by flokli** [comment]
@GuillaumeSeren This is still WIP, as I need to get travis to take the libnotmuch system library, which is why the tests currently fail.

**Comment by GuillaumeSeren** [comment]
@flokli Yes I guessed that

Maybe you can use some help, for this [file](https://github.com/aclements/notmuch/blob/master/.travis.yml)

**Comment by GuillaumeSeren** [comment]
Hey @flokli 
Isn't this PR closely related to  #132 ?

**Comment by GuillaumeSeren** [comment]
Hey @flokli can I help you with that ?

**Comment by flokli** [comment]
@GuillaumeSeren: finally fixed the travis issue, see c27bff335d7bc5df76398ba7b1fd3efd495704ba for details on why this occured. Please review and merge :-)

**Comment by GuillaumeSeren** [comment]
Hey @flokli !
LGTM 👍 
Thank you ! 🍻

**Pull request merged**
